-- Inserir requisitos SOC 2 Type II (64 critérios) - CORRIGIDO
DO $$
DECLARE
  v_framework_id uuid;
BEGIN
  SELECT id INTO v_framework_id FROM gap_analysis_frameworks WHERE nome = 'SOC 2' AND versao = 'Type II' AND is_template = true LIMIT 1;
  
  IF v_framework_id IS NOT NULL THEN
    INSERT INTO gap_analysis_requirements (framework_id, codigo, titulo, descricao, categoria, area_responsavel, peso, obrigatorio, ordem) VALUES
    (v_framework_id, 'CC1.1', 'Estrutura Organizacional Ambiente Controle', 'Organização demonstra comprometimento integridade valores', 'Critérios Comuns - Segurança', 'Governança', 3, true, 1),
    (v_framework_id, 'CC1.2', 'Supervisão Independente', 'Conselho administração independente supervisiona sistema', 'Critérios Comuns - Segurança', 'Governança', 3, true, 2),
    (v_framework_id, 'CC1.3', 'Responsabilidade Autoridade', 'Gestão estabelece autoridade responsabilidade', 'Critérios Comuns - Segurança', 'Governança', 3, true, 3),
    (v_framework_id, 'CC1.4', 'Competência Pessoas', 'Organização demonstra comprometimento competências', 'Critérios Comuns - Segurança', 'RH', 2, true, 4),
    (v_framework_id, 'CC1.5', 'Accountability', 'Organização responsabiliza indivíduos controle interno', 'Critérios Comuns - Segurança', 'Governança', 3, true, 5),
    (v_framework_id, 'CC2.1', 'Comunicação Interna', 'Entidade obtém comunica informação internamente', 'Critérios Comuns - Segurança', 'Comunicação', 2, true, 6),
    (v_framework_id, 'CC2.2', 'Comunicação Externa', 'Entidade comunica informação externamente', 'Critérios Comuns - Segurança', 'Comunicação', 2, true, 7),
    (v_framework_id, 'CC2.3', 'Comunicação Objetivos Mudanças', 'Entidade comunica objetivos controle mudanças', 'Critérios Comuns - Segurança', 'Comunicação', 2, true, 8),
    (v_framework_id, 'CC3.1', 'Especificação Objetivos', 'Entidade especifica objetivos clareza suficiente', 'Critérios Comuns - Segurança', 'Estratégia', 3, true, 9),
    (v_framework_id, 'CC3.2', 'Identificação Análise Riscos', 'Entidade identifica analisa riscos alcance objetivos', 'Critérios Comuns - Segurança', 'Risco', 3, true, 10),
    (v_framework_id, 'CC3.3', 'Avaliação Risco Fraude', 'Entidade considera potencial fraude avaliação riscos', 'Critérios Comuns - Segurança', 'Risco', 3, true, 11),
    (v_framework_id, 'CC3.4', 'Mudanças Significativas', 'Entidade identifica avalia mudanças impactam sistema', 'Critérios Comuns - Segurança', 'Mudança', 2, true, 12),
    (v_framework_id, 'CC4.1', 'Restrição Acesso Lógico', 'Entidade restringe acesso lógico informação ativos', 'Critérios Comuns - Segurança', 'Segurança', 3, true, 13),
    (v_framework_id, 'CC4.2', 'Restrição Acesso Físico', 'Entidade restringe acesso físico instalações ativos', 'Critérios Comuns - Segurança', 'Segurança', 3, true, 14),
    (v_framework_id, 'CC5.1', 'Seleção Desenvolvimento Controles', 'Entidade seleciona desenvolve atividades controle', 'Critérios Comuns - Segurança', 'Controles', 3, true, 15),
    (v_framework_id, 'CC5.2', 'Controles Tecnologia', 'Entidade seleciona desenvolve controles gerais tecnologia', 'Critérios Comuns - Segurança', 'TI', 3, true, 16),
    (v_framework_id, 'CC5.3', 'Implementação Políticas Procedimentos', 'Entidade implementa atividades controle políticas', 'Critérios Comuns - Segurança', 'Controles', 3, true, 17),
    (v_framework_id, 'CC6.1', 'Processos Gestão Riscos', 'Entidade implementa processos gestão riscos', 'Critérios Comuns - Segurança', 'Risco', 3, true, 18),
    (v_framework_id, 'CC6.2', 'Tratamento Riscos', 'Entidade avalia trata riscos identificados', 'Critérios Comuns - Segurança', 'Risco', 3, true, 19),
    (v_framework_id, 'CC6.3', 'Requisitos Conformidade', 'Entidade identifica impõe requisitos conformidade', 'Critérios Comuns - Segurança', 'Compliance', 2, true, 20),
    (v_framework_id, 'CC7.1', 'Detecção Ameaças', 'Detectar analisar anomalias eventos indicam ameaças', 'Critérios Comuns - Segurança', 'Segurança', 3, true, 21),
    (v_framework_id, 'CC7.2', 'Resposta Incidentes', 'Entidade responde incidentes segurança identificados', 'Critérios Comuns - Segurança', 'Incidentes', 3, true, 22),
    (v_framework_id, 'CC7.3', 'Comunicação Incidentes', 'Entidade comunica incidentes partes apropriadas', 'Critérios Comuns - Segurança', 'Comunicação', 2, true, 23),
    (v_framework_id, 'CC7.4', 'Mitigação Recuperação', 'Entidade mitiga impactos recupera incidentes', 'Critérios Comuns - Segurança', 'Continuidade', 3, true, 24),
    (v_framework_id, 'CC8.1', 'Autorização Aprovação Mudanças', 'Entidade autoriza aprova testa documenta mudanças', 'Critérios Comuns - Segurança', 'Mudança', 3, true, 25),
    (v_framework_id, 'CC9.1', 'Gestão Fornecedores', 'Entidade identifica avalia gerencia fornecedores', 'Critérios Comuns - Segurança', 'Fornecedores', 2, true, 26),
    (v_framework_id, 'CC9.2', 'Monitoramento Fornecedores', 'Entidade monitora desempenho conformidade fornecedores', 'Critérios Comuns - Segurança', 'Fornecedores', 2, true, 27),
    (v_framework_id, 'A1.1', 'Disponibilidade Processamento', 'Sistema disponível operação uso conforme acordado', 'Disponibilidade', 'Operações', 3, true, 28),
    (v_framework_id, 'A1.2', 'Capacidade Recursos', 'Entidade mantém capacidade suficiente recursos', 'Disponibilidade', 'Capacidade', 3, true, 29),
    (v_framework_id, 'A1.3', 'Monitoramento Disponibilidade', 'Entidade monitora disponibilidade sistema', 'Disponibilidade', 'Monitoramento', 3, true, 30),
    (v_framework_id, 'A1.4', 'Recuperação Incidentes Disponibilidade', 'Entidade responde recupera incidentes afetam disponibilidade', 'Disponibilidade', 'Continuidade', 3, true, 31),
    (v_framework_id, 'PI1.1', 'Integridade Processamento', 'Sistema processa informação completa precisa oportuna autorizada', 'Integridade de Processamento', 'Processos', 3, true, 32),
    (v_framework_id, 'PI1.2', 'Controles Processamento', 'Entidade implementa controles qualidade processamento', 'Integridade de Processamento', 'Controles', 3, true, 33),
    (v_framework_id, 'PI1.3', 'Validação Dados', 'Entidade valida integridade acurácia dados', 'Integridade de Processamento', 'Dados', 3, true, 34),
    (v_framework_id, 'PI1.4', 'Detecção Correção Erros', 'Entidade detecta corrige erros processamento', 'Integridade de Processamento', 'Processos', 3, true, 35),
    (v_framework_id, 'PI1.5', 'Monitoramento Integridade', 'Entidade monitora integridade processamento sistema', 'Integridade de Processamento', 'Monitoramento', 3, true, 36),
    (v_framework_id, 'C1.1', 'Coleta Informação Confidencial', 'Entidade coleta informações confidenciais conforme objetivos', 'Confidencialidade', 'Dados', 3, true, 37),
    (v_framework_id, 'C1.2', 'Proteção Informação Confidencial', 'Entidade protege informações confidenciais acesso divulgação', 'Confidencialidade', 'Segurança', 3, true, 38),
    (v_framework_id, 'C1.3', 'Descarte Informação Confidencial', 'Entidade descarta informações confidenciais forma segura', 'Confidencialidade', 'Dados', 3, true, 39),
    (v_framework_id, 'C1.4', 'Monitoramento Confidencialidade', 'Entidade monitora acesso uso informações confidenciais', 'Confidencialidade', 'Monitoramento', 3, true, 40),
    (v_framework_id, 'P1.1', 'Aviso Consentimento Privacidade', 'Entidade fornece aviso obtém consentimento coleta uso', 'Privacidade', 'Privacidade', 3, true, 41),
    (v_framework_id, 'P1.2', 'Escolha Consentimento', 'Entidade comunica escolhas consentimento disponíveis', 'Privacidade', 'Privacidade', 3, true, 42),
    (v_framework_id, 'P2.1', 'Coleta Dados Pessoais', 'Entidade coleta dados pessoais consistente objetivos', 'Privacidade', 'Privacidade', 3, true, 43),
    (v_framework_id, 'P3.1', 'Uso Retenção Dados Pessoais', 'Entidade usa retém dados pessoais consistente aviso', 'Privacidade', 'Privacidade', 3, true, 44),
    (v_framework_id, 'P3.2', 'Descarte Dados Pessoais', 'Entidade descarta dados pessoais forma segura', 'Privacidade', 'Privacidade', 3, true, 45),
    (v_framework_id, 'P4.1', 'Acesso Dados Pessoais', 'Entidade fornece acesso correção eliminação dados pessoais', 'Privacidade', 'Privacidade', 3, true, 46),
    (v_framework_id, 'P4.2', 'Correção Dados Pessoais', 'Entidade corrige dados pessoais solicitação', 'Privacidade', 'Privacidade', 2, true, 47),
    (v_framework_id, 'P4.3', 'Eliminação Dados Pessoais', 'Entidade elimina dados pessoais solicitação', 'Privacidade', 'Privacidade', 2, true, 48),
    (v_framework_id, 'P5.1', 'Divulgação Terceiros', 'Entidade divulga dados pessoais terceiros conforme aviso consentimento', 'Privacidade', 'Privacidade', 3, true, 49),
    (v_framework_id, 'P5.2', 'Acordos Terceiros', 'Entidade estabelece acordos terceiros proteção dados pessoais', 'Privacidade', 'Privacidade', 3, true, 50),
    (v_framework_id, 'P6.1', 'Qualidade Dados Pessoais', 'Entidade mantém dados pessoais precisos completos relevantes', 'Privacidade', 'Dados', 2, true, 51),
    (v_framework_id, 'P6.2', 'Correção Dados Imprecisos', 'Entidade corrige dados pessoais imprecisos incompletos', 'Privacidade', 'Dados', 2, true, 52),
    (v_framework_id, 'P7.1', 'Monitoramento Conformidade Privacidade', 'Entidade monitora conformidade objetivos privacidade', 'Privacidade', 'Compliance', 3, true, 53),
    (v_framework_id, 'P7.2', 'Violações Privacidade', 'Entidade responde investiga violações privacidade', 'Privacidade', 'Incidentes', 3, true, 54),
    (v_framework_id, 'P8.1', 'Questionamentos Reclamações', 'Entidade responde questionamentos reclamações privacidade', 'Privacidade', 'Comunicação', 2, true, 55),
    (v_framework_id, 'P8.2', 'Comunicação Violações', 'Entidade comunica violações privacidade afetados', 'Privacidade', 'Comunicação', 3, true, 56),
    (v_framework_id, 'M1', 'Backup Recuperação', 'Entidade mantém backups dados recuperação', 'Adicionais Operacionais', 'Backup', 3, true, 57),
    (v_framework_id, 'M2', 'Plano Continuidade Negócio', 'Entidade mantém plano continuidade recuperação desastres', 'Adicionais Operacionais', 'Continuidade', 3, true, 58),
    (v_framework_id, 'M3', 'Gestão Patches', 'Entidade mantém atualiza patches segurança sistemas', 'Adicionais Operacionais', 'TI', 3, true, 59),
    (v_framework_id, 'M4', 'Criptografia Dados', 'Entidade criptografa dados trânsito repouso', 'Adicionais Operacionais', 'Segurança', 3, true, 60),
    (v_framework_id, 'M5', 'Testes Segurança', 'Entidade realiza testes segurança vulnerabilidade penetração', 'Adicionais Operacionais', 'Segurança', 2, true, 61),
    (v_framework_id, 'M6', 'Gestão Vulnerabilidades', 'Entidade identifica avalia remedeia vulnerabilidades', 'Adicionais Operacionais', 'Segurança', 3, true, 62),
    (v_framework_id, 'M7', 'Treinamento Conscientização', 'Entidade fornece treinamento conscientização segurança privacidade', 'Adicionais Operacionais', 'Treinamento', 2, true, 63),
    (v_framework_id, 'M8', 'Avaliação Controles', 'Entidade avalia design eficácia operacional controles', 'Adicionais Operacionais', 'Auditoria', 3, true, 64);
  END IF;
END $$;