-- Inserir requisitos LGPD (65 artigos)
INSERT INTO gap_analysis_requirements (framework_id, codigo, titulo, descricao, categoria, area_responsavel, peso, obrigatorio, ordem)
SELECT 
  f.id as framework_id,
  req.codigo,
  req.titulo,
  req.descricao,
  req.categoria,
  req.area_responsavel,
  req.peso,
  req.obrigatorio,
  req.ordem
FROM gap_analysis_frameworks f
CROSS JOIN (VALUES
  -- Capítulo I - Disposições Preliminares
  ('Art. 1º', 'Objeto da Lei', 'Disciplina o tratamento de dados pessoais por pessoa natural ou jurídica de direito público ou privado, com o objetivo de proteger os direitos fundamentais de liberdade e de privacidade.', 'Disposições Preliminares', 'Jurídico', 3, true, 1),
  ('Art. 2º', 'Fundamentos da Proteção de Dados', 'Estabelece fundamentos: respeito à privacidade, autodeterminação informativa, liberdade de expressão, inviolabilidade da intimidade, defesa do consumidor, direitos humanos, livre desenvolvimento da personalidade, dignidade e exercício da cidadania.', 'Disposições Preliminares', 'Compliance', 3, true, 2),
  ('Art. 3º', 'Âmbito de Aplicação', 'Aplica-se a qualquer operação de tratamento realizada no Brasil, quando objetivo seja oferta de produtos ou serviços no território nacional, ou quando dados tenham sido coletados no Brasil.', 'Disposições Preliminares', 'Jurídico', 3, true, 3),
  ('Art. 4º', 'Não Aplicação da Lei', 'Define situações em que a lei não se aplica: tratamento por pessoa natural para fins particulares, fins jornalísticos e artísticos, segurança pública, defesa nacional, segurança do Estado, ou investigação e repressão de infrações penais.', 'Disposições Preliminares', 'Jurídico', 2, true, 4),
  ('Art. 5º', 'Definições', 'Define 18 conceitos-chave: dado pessoal, dado sensível, titular, controlador, operador, encarregado, agentes de tratamento, tratamento, anonimização, consentimento, bloqueio, eliminação, transferência internacional, uso compartilhado, banco de dados, relatório de impacto, orgão de pesquisa, autoridade nacional.', 'Disposições Preliminares', 'Compliance', 3, true, 5),
  
  -- Capítulo II - Tratamento de Dados Pessoais
  ('Art. 6º', 'Atividades de Tratamento', 'Estabelece que atividades de tratamento devem observar boa-fé e 10 princípios: finalidade, adequação, necessidade, livre acesso, qualidade dos dados, transparência, segurança, prevenção, não discriminação, responsabilização e prestação de contas.', 'Tratamento de Dados', 'Compliance', 3, true, 6),
  ('Art. 7º', 'Bases Legais', 'Define 10 hipóteses legais para tratamento: consentimento, cumprimento de obrigação legal, execução de políticas públicas, realização de estudos, execução de contrato, exercício regular de direitos, proteção da vida, tutela da saúde, legítimo interesse, proteção do crédito.', 'Tratamento de Dados', 'Jurídico', 3, true, 7),
  ('Art. 8º', 'Consentimento', 'O consentimento deve ser fornecido por escrito ou por outro meio que demonstre a manifestação de vontade do titular, de forma destacada das demais cláusulas contratuais.', 'Tratamento de Dados', 'Compliance', 3, true, 8),
  ('Art. 9º', 'Revogação do Consentimento', 'O titular tem direito a revogar o consentimento a qualquer momento, mediante manifestação expressa, por procedimento gratuito e facilitado.', 'Tratamento de Dados', 'Compliance', 3, true, 9),
  ('Art. 10', 'Legítimo Interesse', 'Define que o legítimo interesse deve considerar direitos e liberdades fundamentais do titular, e pode ser usado apenas para finalidades legítimas, consideradas a partir de situações concretas.', 'Tratamento de Dados', 'Jurídico', 2, true, 10),
  ('Art. 11', 'Dados Sensíveis', 'Define bases legais para tratamento de dados sensíveis: consentimento específico, cumprimento de obrigação legal, políticas públicas, estudos por órgãos de pesquisa, exercício de direitos, proteção da vida, tutela da saúde, prevenção à fraude.', 'Tratamento de Dados', 'Compliance', 3, true, 11),
  ('Art. 12', 'Comunicação ou Uso Compartilhado', 'Define que a comunicação ou uso compartilhado entre controladores de dados pessoais deve observar as hipóteses previstas no art. 7º.', 'Tratamento de Dados', 'TI', 2, true, 12),
  ('Art. 13', 'Estudos em Saúde Pública', 'Permite estudos em saúde pública sem consentimento, desde que anonimizados sempre que possível e respeitados os princípios da lei.', 'Tratamento de Dados', 'Saúde', 2, false, 13),
  ('Art. 14', 'Tratamento de Dados de Crianças', 'O tratamento de dados de crianças e adolescentes deve ser realizado no melhor interesse do menor, com consentimento específico dos pais ou responsável legal.', 'Tratamento de Dados', 'Compliance', 3, true, 14),
  ('Art. 15', 'Término do Tratamento', 'Define situações de término: verificação de que a finalidade foi alcançada, fim do período de tratamento, comunicação do titular, ou determinação da autoridade nacional.', 'Tratamento de Dados', 'Compliance', 2, true, 15),
  ('Art. 16', 'Eliminação de Dados', 'Após término do tratamento, os dados devem ser eliminados, salvo quando necessário para: cumprimento de obrigação legal, estudo por órgão de pesquisa, transferência a terceiro (respeitados os requisitos), ou uso exclusivo do controlador (vedado acesso por terceiro e anonimizados).', 'Tratamento de Dados', 'TI', 3, true, 16),
  
  -- Capítulo III - Direitos do Titular
  ('Art. 17', 'Direito à Informação', 'Toda pessoa natural tem assegurada a titularidade de seus dados pessoais e garantidos os direitos fundamentais de liberdade, intimidade e privacidade.', 'Direitos do Titular', 'Compliance', 3, true, 17),
  ('Art. 18', 'Direitos do Titular', 'O titular tem direito a obter do controlador: confirmação de existência de tratamento, acesso aos dados, correção, anonimização/bloqueio/eliminação, portabilidade, eliminação do consentimento, informação sobre compartilhamento, informação sobre negativa de consentimento, e revogação do consentimento.', 'Direitos do Titular', 'Compliance', 3, true, 18),
  ('Art. 19', 'Confirmação e Acesso', 'A confirmação de tratamento ou o acesso aos dados será fornecida imediatamente em formato simplificado ou em até 15 dias em formato completo.', 'Direitos do Titular', 'TI', 3, true, 19),
  ('Art. 20', 'Portabilidade de Dados', 'O titular tem direito a solicitar a portabilidade de seus dados pessoais a outro fornecedor de serviço ou produto, mediante requisição expressa, respeitados os segredos comercial e industrial.', 'Direitos do Titular', 'TI', 3, true, 20),
  ('Art. 21', 'Decisões Automatizadas', 'O titular tem direito a solicitar a revisão de decisões tomadas unicamente com base em tratamento automatizado que afetem seus interesses.', 'Direitos do Titular', 'TI', 3, true, 21),
  
  -- Capítulo IV - Agentes de Tratamento
  ('Art. 37', 'Controlador e Operador', 'O controlador e o operador devem manter registro das operações de tratamento de dados pessoais que realizarem.', 'Agentes de Tratamento', 'TI', 3, true, 22),
  ('Art. 38', 'Autoridade Nacional', 'A autoridade nacional poderá determinar ao controlador que elabore relatório de impacto à proteção de dados pessoais.', 'Agentes de Tratamento', 'Compliance', 3, true, 23),
  ('Art. 39', 'Operador', 'O operador deverá realizar o tratamento segundo as instruções fornecidas pelo controlador.', 'Agentes de Tratamento', 'TI', 3, true, 24),
  ('Art. 40', 'Comunicação de Incidente', 'O controlador deverá comunicar à autoridade nacional e ao titular a ocorrência de incidente de segurança que possa acarretar risco ou dano relevante aos titulares.', 'Agentes de Tratamento', 'Segurança', 3, true, 25),
  ('Art. 41', 'Encarregado (DPO)', 'O controlador deverá indicar encarregado pelo tratamento de dados pessoais. A identidade e as informações de contato do encarregado deverão ser divulgadas publicamente.', 'Agentes de Tratamento', 'Compliance', 3, true, 26),
  ('Art. 42', 'Responsabilidade do Controlador', 'O controlador ou o operador que causar dano patrimonial, moral, individual ou coletivo, em violação à legislação de proteção de dados pessoais, é obrigado a repará-lo.', 'Agentes de Tratamento', 'Jurídico', 3, true, 27),
  ('Art. 43', 'Inversão do Ônus da Prova', 'Os agentes de tratamento só não serão responsabilizados quando provarem que não realizaram o tratamento de dados pessoais que lhes é atribuído, que realizaram o tratamento mas não houve violação, ou que o dano é decorrente de culpa exclusiva do titular ou de terceiro.', 'Agentes de Tratamento', 'Jurídico', 3, true, 28),
  ('Art. 44', 'Responsabilidade do Operador', 'O operador responde solidariamente pelos danos causados pelo tratamento quando descumprir as obrigações da legislação de proteção de dados ou quando não tiver seguido as instruções lícitas do controlador.', 'Agentes de Tratamento', 'Jurídico', 3, true, 29),
  ('Art. 45', 'Excludentes de Responsabilidade', 'As hipóteses de exclusão de responsabilidade previstas não são aplicáveis em caso de dano decorrente de violação da segurança dos dados.', 'Agentes de Tratamento', 'Segurança', 3, true, 30),
  
  -- Capítulo V - Transferência Internacional
  ('Art. 33', 'Transferência Internacional', 'A transferência internacional de dados pessoais somente é permitida em casos específicos: países com nível adequado de proteção, garantias contratuais, cooperação jurídica, proteção da vida, autorização da ANPD, acordos de cooperação, ou consentimento.', 'Transferência Internacional', 'Jurídico', 3, true, 31),
  ('Art. 34', 'Nível Adequado de Proteção', 'O nível de proteção de dados do país estrangeiro será avaliado pela autoridade nacional, considerando as normas gerais e setoriais da legislação, garantias de direitos fundamentais, e características do tratamento.', 'Transferência Internacional', 'Compliance', 2, true, 32),
  ('Art. 35', 'Cláusulas Contratuais Específicas', 'A transferência pode ocorrer por meio de cláusulas contratuais específicas ou cláusulas-padrão contratuais aprovadas pela autoridade nacional.', 'Transferência Internacional', 'Jurídico', 2, true, 33),
  ('Art. 36', 'Cooperação Jurídica Internacional', 'A autoridade nacional poderá dispor sobre cláusulas-padrão contratuais, cláusulas contratuais específicas, normas corporativas globais, e selos, certificados e códigos de conduta.', 'Transferência Internacional', 'Jurídico', 2, false, 34),
  
  -- Capítulo VI - Segurança e Boas Práticas
  ('Art. 46', 'Medidas de Segurança', 'Os agentes de tratamento devem adotar medidas de segurança, técnicas e administrativas aptas a proteger os dados pessoais de acessos não autorizados e de situações acidentais ou ilícitas de destruição, perda, alteração, comunicação ou qualquer forma de tratamento inadequado ou ilícito.', 'Segurança e Boas Práticas', 'Segurança', 3, true, 35),
  ('Art. 47', 'Comunicação de Incidente', 'Os agentes de tratamento ou qualquer outra pessoa que intervenha em uma das fases do tratamento obriga-se a garantir a segurança da informação prevista nesta Lei em relação aos dados pessoais.', 'Segurança e Boas Práticas', 'Segurança', 3, true, 36),
  ('Art. 48', 'Prazo de Conservação', 'O controlador deverá comunicar à autoridade nacional e ao titular a ocorrência de incidente de segurança que possa acarretar risco ou dano relevante aos titulares.', 'Segurança e Boas Práticas', 'Segurança', 3, true, 37),
  ('Art. 49', 'Padrões Técnicos', 'Os sistemas utilizados para o tratamento de dados pessoais devem ser estruturados de forma a atender aos requisitos de segurança, aos padrões de boas práticas e de governança.', 'Segurança e Boas Práticas', 'TI', 3, true, 38),
  ('Art. 50', 'Boas Práticas e Governança', 'Controladores e operadores podem formular regras de boas práticas e de governança que estabeleçam condições de organização, regime de funcionamento, procedimentos, normas de segurança, padrões técnicos, obrigações específicas, ações educativas, mecanismos internos de supervisão e de mitigação de riscos.', 'Segurança e Boas Práticas', 'Compliance', 2, false, 39),
  
  -- Capítulo VII - Autoridade Nacional de Proteção de Dados (ANPD)
  ('Art. 55-A', 'Criação da ANPD', 'Fica criada a Autoridade Nacional de Proteção de Dados (ANPD), órgão da administração pública federal, integrante da Presidência da República.', 'ANPD', 'Compliance', 2, true, 40),
  ('Art. 55-B', 'Natureza Transitória', 'A ANPD é composta por Conselho Diretor, órgão máximo de direção, por Conselho Nacional de Proteção de Dados Pessoais e da Privacidade, por Corregedoria, por Ouvidoria, por órgão de assessoramento jurídico próprio, e por unidades administrativas e unidades especializadas necessárias.', 'ANPD', 'Compliance', 1, false, 41),
  ('Art. 55-C', 'Autonomia Técnica', 'A ANPD terá autonomia técnica e decisória.', 'ANPD', 'Compliance', 2, false, 42),
  ('Art. 55-D', 'Conselho Diretor', 'O Conselho Diretor da ANPD será composto por 5 diretores, incluído o Diretor-Presidente.', 'ANPD', 'Compliance', 1, false, 43),
  ('Art. 55-J', 'Competências da ANPD', 'Compete à ANPD: zelar pela proteção dos dados pessoais, elaborar diretrizes, fiscalizar e aplicar sanções, promover educação, realizar consultas públicas, editar regulamentos e procedimentos, ouvir entidades, articular-se com autoridades reguladoras, comunicar infrações, estimular adoção de padrões técnicos, e promover cooperação.', 'ANPD', 'Compliance', 3, true, 44),
  ('Art. 55-K', 'Processo Administrativo', 'A aplicação das sanções previstas nesta Lei compete exclusivamente à ANPD.', 'ANPD', 'Compliance', 3, true, 45),
  ('Art. 55-L', 'Relatório de Impacto', 'Constituem receitas da ANPD: dotações orçamentárias, doações, e o produto da cobrança de emolumentos por serviços prestados.', 'ANPD', 'Compliance', 1, false, 46),
  
  -- Capítulo VIII - Sanções Administrativas
  ('Art. 52', 'Sanções Aplicáveis', 'Os agentes de tratamento que infringirem o disposto nesta Lei ficam sujeitos às seguintes sanções: advertência, multa simples (até 2% do faturamento, limitada a R$ 50 milhões), multa diária, publicização da infração, bloqueio dos dados pessoais, eliminação dos dados pessoais, suspensão parcial do banco de dados, suspensão do exercício da atividade, e proibição parcial ou total do exercício de atividades.', 'Sanções', 'Compliance', 3, true, 47),
  ('Art. 53', 'Dosimetria das Sanções', 'Na aplicação das sanções, serão considerados: gravidade e natureza das infrações, boa-fé do infrator, vantagem auferida, condição econômica, reincidência, grau de dano, cooperação, adoção de mecanismos e procedimentos internos capazes de minimizar dano, adoção de política de boas práticas, pronta adoção de medidas corretivas, e proporcionalidade entre gravidade da falta e intensidade da sanção.', 'Sanções', 'Compliance', 3, true, 48),
  ('Art. 54', 'Receita das Multas', 'A aplicação das sanções não exclui a aplicação de sanções administrativas, civis ou penais previstas na legislação.', 'Sanções', 'Jurídico', 2, true, 49),
  
  -- Artigos de Disposições Finais e Transitórias
  ('Art. 22', 'Defesa em Juízo', 'A defesa dos interesses e dos direitos dos titulares de dados poderá ser exercida em juízo, individual ou coletivamente.', 'Disposições Finais', 'Jurídico', 2, true, 50),
  ('Art. 23', 'Proteção de Dados na Internet', 'O tratamento de dados pessoais previsto no art. 7º, VII, relativo ao legítimo interesse, deverá ser informado ao titular e à autoridade nacional, observados os segredos comercial e industrial.', 'Disposições Finais', 'Compliance', 2, true, 51),
  ('Art. 24', 'Leis Especiais', 'Leis especiais que versem sobre dados pessoais continuam em vigor, desde que não contrariem as disposições desta Lei.', 'Disposições Finais', 'Jurídico', 1, false, 52),
  ('Art. 25', 'Interpretação', 'Esta Lei deverá ser interpretada em harmonia com os princípios e direitos fundamentais previstos na Constituição.', 'Disposições Finais', 'Jurídico', 2, true, 53),
  ('Art. 26', 'Responsabilidade Solidária', 'O uso compartilhado de dados pessoais pelo Poder Público deve atender a finalidades específicas de execução de políticas públicas e atribuição legal pelos órgãos e pelas entidades públicas.', 'Disposições Finais', 'Compliance', 2, true, 54),
  ('Art. 27', 'Comunicação entre Controladores', 'A comunicação ou o uso compartilhado de dados pessoais de pessoa jurídica de direito público a pessoa de direito privado será informado à autoridade nacional.', 'Disposições Finais', 'Compliance', 2, true, 55),
  ('Art. 28', 'Dispensa do Consentimento', 'A autoridade nacional poderá solicitar a órgãos e entidades do poder público a publicação de informações sobre o uso compartilhado de dados.', 'Disposições Finais', 'Compliance', 1, false, 56),
  ('Art. 29', 'Colaboração Internacional', 'A autoridade nacional poderá dispor sobre padrões de interoperabilidade para fins de portabilidade, livre acesso aos dados e segurança.', 'Disposições Finais', 'TI', 1, false, 57),
  ('Art. 30', 'Exceções', 'A autoridade nacional poderá estabelecer normas complementares para as atividades de comunicação e de uso compartilhado de dados pessoais.', 'Disposições Finais', 'Compliance', 1, false, 58),
  ('Art. 31', 'Extraterritorialidade', 'Quando o tratamento for efetuado por pessoa jurídica de direito público, deverá ser publicado relatório de impacto à proteção de dados pessoais.', 'Disposições Finais', 'Compliance', 2, false, 59),
  ('Art. 32', 'Cadastro Nacional', 'A autoridade nacional poderá solicitar relatório de impacto à proteção de dados pessoais a controladores.', 'Disposições Finais', 'Compliance', 2, false, 60),
  ('Art. 51', 'Códigos de Conduta', 'Controladores e operadores poderão estabelecer códigos de conduta e boas práticas, observadas as disposições desta Lei.', 'Disposições Finais', 'Compliance', 1, false, 61),
  ('Art. 56', 'Regulamentação pelo Poder Executivo', 'O Poder Executivo poderá regulamentar a aplicação desta Lei.', 'Disposições Finais', 'Jurídico', 1, false, 62),
  ('Art. 57', 'Revogação de Dispositivos', 'Esta Lei revoga dispositivos do Código de Defesa do Consumidor e da Lei de Acesso à Informação que tratem de dados pessoais.', 'Disposições Finais', 'Jurídico', 1, false, 63),
  ('Art. 58', 'Prazo para Adequação', 'Esta Lei entra em vigor após 24 meses de sua publicação oficial.', 'Disposições Finais', 'Compliance', 1, false, 64),
  ('Art. 59', 'Vigência', 'Ficam revogados dispositivos de outras leis que contrariem o disposto nesta Lei.', 'Disposições Finais', 'Jurídico', 1, false, 65)
) AS req(codigo, titulo, descricao, categoria, area_responsavel, peso, obrigatorio, ordem)
WHERE f.nome = 'LGPD' AND f.versao = '2020';

-- Inserir requisitos GDPR (99 artigos)
INSERT INTO gap_analysis_requirements (framework_id, codigo, titulo, descricao, categoria, area_responsavel, peso, obrigatorio, ordem)
SELECT 
  f.id as framework_id,
  req.codigo,
  req.titulo,
  req.descricao,
  req.categoria,
  req.area_responsavel,
  req.peso,
  req.obrigatorio,
  req.ordem
FROM gap_analysis_frameworks f
CROSS JOIN (VALUES
  -- Chapter I - General Provisions
  ('Art. 1', 'Subject Matter and Objectives', 'This Regulation lays down rules relating to the protection of natural persons with regard to the processing of personal data and rules relating to the free movement of personal data.', 'General Provisions', 'Legal', 3, true, 1),
  ('Art. 2', 'Material Scope', 'This Regulation applies to the processing of personal data wholly or partly by automated means and to the processing other than by automated means of personal data which form part of a filing system or are intended to form part of a filing system.', 'General Provisions', 'Legal', 3, true, 2),
  ('Art. 3', 'Territorial Scope', 'This Regulation applies to the processing of personal data in the context of the activities of an establishment of a controller or a processor in the Union, regardless of whether the processing takes place in the Union or not.', 'General Provisions', 'Legal', 3, true, 3),
  ('Art. 4', 'Definitions', 'Defines 26 key terms including personal data, processing, restriction of processing, profiling, pseudonymisation, filing system, controller, processor, recipient, third party, consent, personal data breach, genetic data, biometric data, data concerning health, main establishment, representative, enterprise, group of undertaking, binding corporate rules, supervisory authority, supervisory authority concerned, cross-border processing, relevant and reasoned objection, information society service, and international organisation.', 'General Provisions', 'Compliance', 3, true, 4),
  
  -- Chapter II - Principles
  ('Art. 5', 'Principles Relating to Processing', 'Personal data shall be: processed lawfully, fairly and transparently; collected for specified, explicit and legitimate purposes; adequate, relevant and limited; accurate and kept up to date; kept in a form which permits identification for no longer than necessary; processed in a manner that ensures appropriate security.', 'Principles', 'Compliance', 3, true, 5),
  ('Art. 6', 'Lawfulness of Processing', 'Processing shall be lawful only if at least one of the following applies: consent, contract, legal obligation, vital interests, public interest, or legitimate interests.', 'Principles', 'Legal', 3, true, 6),
  ('Art. 7', 'Conditions for Consent', 'Where processing is based on consent, the controller shall be able to demonstrate that the data subject has consented. Consent must be freely given, specific, informed and unambiguous.', 'Principles', 'Compliance', 3, true, 7),
  ('Art. 8', 'Conditions for Children Consent', 'Where the child is below the age of 16 years, processing shall be lawful only if consent is given by the holder of parental responsibility.', 'Principles', 'Compliance', 3, true, 8),
  ('Art. 9', 'Processing of Special Categories', 'Processing of personal data revealing racial or ethnic origin, political opinions, religious or philosophical beliefs, trade union membership, genetic data, biometric data, health data, or data concerning sex life is prohibited, except in specific circumstances.', 'Principles', 'Compliance', 3, true, 9),
  ('Art. 10', 'Processing of Criminal Convictions', 'Processing of personal data relating to criminal convictions and offences shall be carried out only under the control of official authority or when authorised by Union or Member State law.', 'Principles', 'Legal', 3, true, 10),
  ('Art. 11', 'Processing Not Requiring Identification', 'If the purposes for which a controller processes personal data do not require the identification of a data subject by the controller, the controller shall not be obliged to maintain additional information.', 'Principles', 'Compliance', 2, true, 11),
  
  -- Chapter III - Rights of the Data Subject
  ('Art. 12', 'Transparent Information and Communication', 'The controller shall take appropriate measures to provide any information and any communication relating to processing to the data subject in a concise, transparent, intelligible and easily accessible form, using clear and plain language.', 'Rights of Data Subject', 'Compliance', 3, true, 12),
  ('Art. 13', 'Information When Data Collected', 'Where personal data are collected from the data subject, the controller shall provide: identity and contact details, purposes and legal basis, legitimate interests, recipients, transfers, retention period, data subject rights, right to withdraw consent, right to lodge complaint, and whether provision is statutory requirement.', 'Rights of Data Subject', 'Compliance', 3, true, 13),
  ('Art. 14', 'Information Not Obtained from Subject', 'Where personal data have not been obtained from the data subject, the controller shall provide all information of Article 13 plus the categories of personal data concerned and the source of the data.', 'Rights of Data Subject', 'Compliance', 3, true, 14),
  ('Art. 15', 'Right of Access', 'The data subject shall have the right to obtain from the controller confirmation as to whether or not personal data concerning him or her are being processed, and access to the personal data and additional information.', 'Rights of Data Subject', 'Compliance', 3, true, 15),
  ('Art. 16', 'Right to Rectification', 'The data subject shall have the right to obtain from the controller without undue delay the rectification of inaccurate personal data and to have incomplete personal data completed.', 'Rights of Data Subject', 'Compliance', 3, true, 16),
  ('Art. 17', 'Right to Erasure (Right to be Forgotten)', 'The data subject shall have the right to obtain from the controller the erasure of personal data concerning him or her without undue delay in specific circumstances.', 'Rights of Data Subject', 'Compliance', 3, true, 17),
  ('Art. 18', 'Right to Restriction of Processing', 'The data subject shall have the right to obtain from the controller restriction of processing in specific cases.', 'Rights of Data Subject', 'Compliance', 3, true, 18),
  ('Art. 19', 'Notification Obligation', 'The controller shall communicate any rectification or erasure of personal data or restriction of processing to each recipient to whom the personal data have been disclosed.', 'Rights of Data Subject', 'IT', 3, true, 19),
  ('Art. 20', 'Right to Data Portability', 'The data subject shall have the right to receive the personal data concerning him or her in a structured, commonly used and machine-readable format and have the right to transmit those data to another controller.', 'Rights of Data Subject', 'IT', 3, true, 20),
  ('Art. 21', 'Right to Object', 'The data subject shall have the right to object, on grounds relating to his or her particular situation, at any time to processing of personal data concerning him or her based on legitimate interests or performance of a task in the public interest.', 'Rights of Data Subject', 'Compliance', 3, true, 21),
  ('Art. 22', 'Automated Individual Decision-Making', 'The data subject shall have the right not to be subject to a decision based solely on automated processing, including profiling, which produces legal effects or similarly significantly affects him or her.', 'Rights of Data Subject', 'IT', 3, true, 22),
  ('Art. 23', 'Restrictions', 'Union or Member State law may restrict the scope of the obligations and rights when such a restriction respects the essence of fundamental rights and freedoms and is a necessary and proportionate measure.', 'Rights of Data Subject', 'Legal', 2, true, 23),
  
  -- Chapter IV - Controller and Processor
  ('Art. 24', 'Responsibility of Controller', 'The controller shall implement appropriate technical and organisational measures to ensure and to be able to demonstrate that processing is performed in accordance with this Regulation (accountability).', 'Controller and Processor', 'Compliance', 3, true, 24),
  ('Art. 25', 'Data Protection by Design and Default', 'The controller shall implement appropriate technical and organisational measures for ensuring that, by default, only personal data which are necessary for each specific purpose are processed (privacy by design and by default).', 'Controller and Processor', 'IT', 3, true, 25),
  ('Art. 26', 'Joint Controllers', 'Where two or more controllers jointly determine the purposes and means of processing, they shall be joint controllers and shall determine their respective responsibilities in a transparent manner.', 'Controller and Processor', 'Legal', 2, true, 26),
  ('Art. 27', 'Representatives of Controllers Not in Union', 'Where processing is to be carried out by a controller not established in the Union, the controller shall designate a representative in the Union.', 'Controller and Processor', 'Legal', 2, false, 27),
  ('Art. 28', 'Processor', 'Where processing is to be carried out on behalf of a controller, the controller shall use only processors providing sufficient guarantees and the processing by a processor shall be governed by a contract or other legal act.', 'Controller and Processor', 'Legal', 3, true, 28),
  ('Art. 29', 'Processing Under Authority', 'The processor and any person acting under the authority of the controller or of the processor, who has access to personal data, shall not process those data except on instructions from the controller.', 'Controller and Processor', 'IT', 3, true, 29),
  ('Art. 30', 'Records of Processing Activities', 'Each controller and processor shall maintain a record of processing activities under its responsibility containing: name and contact details, purposes of processing, categories of data subjects and personal data, categories of recipients, transfers, time limits, and description of security measures.', 'Controller and Processor', 'Compliance', 3, true, 30),
  ('Art. 31', 'Cooperation with Supervisory Authority', 'The controller and the processor shall cooperate with the supervisory authority in the performance of its tasks.', 'Controller and Processor', 'Compliance', 3, true, 31),
  ('Art. 32', 'Security of Processing', 'The controller and processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk, including pseudonymisation and encryption, ensuring ongoing confidentiality, ability to restore availability, and regular testing.', 'Controller and Processor', 'Security', 3, true, 32),
  ('Art. 33', 'Notification of Breach to Authority', 'In the case of a personal data breach, the controller shall without undue delay and, where feasible, not later than 72 hours after having become aware of it, notify the personal data breach to the supervisory authority.', 'Controller and Processor', 'Security', 3, true, 33),
  ('Art. 34', 'Communication of Breach to Subject', 'When the personal data breach is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall communicate the personal data breach to the data subject without undue delay.', 'Controller and Processor', 'Security', 3, true, 34),
  ('Art. 35', 'Data Protection Impact Assessment', 'Where a type of processing is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall carry out an assessment of the impact of the envisaged processing operations on the protection of personal data (DPIA).', 'Controller and Processor', 'Compliance', 3, true, 35),
  ('Art. 36', 'Prior Consultation', 'The controller shall consult the supervisory authority prior to processing where a data protection impact assessment indicates that the processing would result in a high risk in the absence of measures taken by the controller to mitigate the risk.', 'Controller and Processor', 'Compliance', 3, true, 36),
  ('Art. 37', 'Designation of DPO', 'The controller and the processor shall designate a data protection officer in cases where: processing is carried out by public authority, core activities require regular monitoring, or core activities consist of processing special categories of data.', 'Controller and Processor', 'Compliance', 3, true, 37),
  ('Art. 38', 'Position of DPO', 'The controller and processor shall ensure that the data protection officer is involved in all issues relating to the protection of personal data and ensure resources and access to personal data and processing operations.', 'Controller and Processor', 'Compliance', 3, true, 38),
  ('Art. 39', 'Tasks of DPO', 'The data protection officer shall have at least the following tasks: inform and advise, monitor compliance, provide advice on DPIA, cooperate with supervisory authority, and act as contact point.', 'Controller and Processor', 'Compliance', 3, true, 39),
  ('Art. 40', 'Codes of Conduct', 'Member States, supervisory authorities, the Board and the Commission shall encourage the drawing up of codes of conduct intended to contribute to the proper application of this Regulation.', 'Controller and Processor', 'Compliance', 1, false, 40),
  ('Art. 41', 'Monitoring of Codes of Conduct', 'Without prejudice to the tasks and powers of the competent supervisory authority, the monitoring of compliance with a code of conduct may be carried out by a body which has an appropriate level of expertise.', 'Controller and Processor', 'Compliance', 1, false, 41),
  ('Art. 42', 'Certification', 'Member States, supervisory authorities, the Board and the Commission shall encourage the establishment of data protection certification mechanisms and seals and marks.', 'Controller and Processor', 'Compliance', 1, false, 42),
  ('Art. 43', 'Certification Bodies', 'Certification shall be issued by certification bodies or by the competent supervisory authority on the basis of criteria approved by the supervisory authority.', 'Controller and Processor', 'Compliance', 1, false, 43),
  
  -- Chapter V - Transfers of Personal Data to Third Countries
  ('Art. 44', 'General Principle for Transfers', 'Any transfer of personal data to a third country or an international organisation shall take place only if the controller and processor comply with the conditions laid down in this Chapter.', 'Transfers', 'Legal', 3, true, 44),
  ('Art. 45', 'Transfers Based on Adequacy Decision', 'A transfer of personal data to a third country may take place where the Commission has decided that the third country ensures an adequate level of protection.', 'Transfers', 'Legal', 3, true, 45),
  ('Art. 46', 'Transfers Subject to Appropriate Safeguards', 'In the absence of an adequacy decision, a controller or processor may transfer personal data to a third country only if the controller or processor has provided appropriate safeguards (BCR, standard contractual clauses, codes of conduct, certification mechanisms).', 'Transfers', 'Legal', 3, true, 46),
  ('Art. 47', 'Binding Corporate Rules', 'The competent supervisory authority shall approve binding corporate rules which are legally binding and apply to all members concerned of the group of undertakings.', 'Transfers', 'Legal', 2, false, 47),
  ('Art. 48', 'Transfers Not Authorised by Union Law', 'Any judgment of a court or tribunal and any decision of an administrative authority of a third country requiring a controller or processor to transfer or disclose personal data may only be recognised or enforceable if based on an international agreement.', 'Transfers', 'Legal', 2, true, 48),
  ('Art. 49', 'Derogations for Specific Situations', 'In the absence of an adequacy decision or appropriate safeguards, a transfer may take place only if: the data subject has explicitly consented, the transfer is necessary for contract performance, important reasons of public interest, legal claims, vital interests, or the transfer is from a public register.', 'Transfers', 'Legal', 3, true, 49),
  ('Art. 50', 'International Cooperation', 'In relation to third countries and international organisations, the Commission and supervisory authorities shall take appropriate steps to develop international cooperation mechanisms to facilitate the effective enforcement of legislation.', 'Transfers', 'Legal', 1, false, 50),
  
  -- Chapter VI - Independent Supervisory Authorities
  ('Art. 51', 'Supervisory Authority', 'Each Member State shall provide for one or more independent public authorities to be responsible for monitoring the application of this Regulation (supervisory authority).', 'Supervisory Authorities', 'Compliance', 2, true, 51),
  ('Art. 52', 'Independence', 'Each supervisory authority shall act with complete independence in performing its tasks and exercising its powers.', 'Supervisory Authorities', 'Compliance', 2, true, 52),
  ('Art. 53', 'General Conditions for Members', 'Member States shall provide that each member of their supervisory authorities shall be appointed by transparent procedure and possess qualifications, experience and skills required to perform duties.', 'Supervisory Authorities', 'Compliance', 1, false, 53),
  ('Art. 54', 'Rules on Establishment', 'Each Member State shall provide by law for: establishment, qualifications and eligibility, rules and procedures for appointment, duration of term, acting in full-time capacity, termination of duties, and rules on conflicts of interest.', 'Supervisory Authorities', 'Compliance', 1, false, 54),
  ('Art. 55', 'Competence', 'Each supervisory authority shall be competent for the performance of the tasks assigned to and the exercise of the powers conferred on it on the territory of its own Member State.', 'Supervisory Authorities', 'Compliance', 2, true, 55),
  ('Art. 56', 'Competence of Lead Authority', 'The supervisory authority of the main establishment or of the single establishment of the controller or processor shall be competent to act as lead supervisory authority for the cross-border processing.', 'Supervisory Authorities', 'Compliance', 2, true, 56),
  ('Art. 57', 'Tasks', 'Each supervisory authority shall: monitor and enforce application, promote public awareness, advise national parliament and government, promote awareness of controllers and processors, handle complaints, conduct investigations, review data protection impact assessments, issue authorisations, advise on processing operations, and contribute to activities of the Board.', 'Supervisory Authorities', 'Compliance', 3, true, 57),
  ('Art. 58', 'Powers', 'Each supervisory authority shall have investigative powers, corrective powers (issue warnings, reprimands, orders, impose limitations, order rectification/erasure/restriction, impose administrative fines), and authorisation and advisory powers.', 'Supervisory Authorities', 'Compliance', 3, true, 58),
  ('Art. 59', 'Activity Reports', 'Each supervisory authority shall draw up an annual report on its activities, which may include a list of types of infringements notified and types of measures taken.', 'Supervisory Authorities', 'Compliance', 1, false, 59),
  
  -- Chapter VII - Cooperation and Consistency
  ('Art. 60', 'Cooperation Between Authorities', 'The lead supervisory authority shall cooperate with the other supervisory authorities concerned in accordance with this Article in an endeavour to reach consensus.', 'Cooperation', 'Compliance', 2, true, 60),
  ('Art. 61', 'Mutual Assistance', 'Supervisory authorities shall provide each other with relevant information and mutual assistance in order to implement and apply this Regulation in a consistent manner.', 'Cooperation', 'Compliance', 2, true, 61),
  ('Art. 62', 'Joint Operations', 'Supervisory authorities shall conduct joint operations including joint investigations and joint enforcement measures in which members or staff from other Member States take part.', 'Cooperation', 'Compliance', 1, false, 62),
  ('Art. 63', 'Consistency Mechanism', 'In order to contribute to the consistent application of this Regulation throughout the Union, the supervisory authorities shall cooperate with each other and the Commission through the consistency mechanism.', 'Cooperation', 'Compliance', 2, true, 63),
  ('Art. 64', 'Opinion of the Board', 'The Board shall issue an opinion where a competent supervisory authority intends to adopt measures concerning several specific situations enumerated in this Article.', 'Cooperation', 'Compliance', 1, false, 64),
  ('Art. 65', 'Dispute Resolution by Board', 'In order to ensure the correct and consistent application of this Regulation, the Board shall adopt a binding decision when a supervisory authority has raised a relevant and reasoned objection.', 'Cooperation', 'Compliance', 2, false, 65),
  ('Art. 66', 'Urgency Procedure', 'In exceptional circumstances, where a supervisory authority considers that there is an urgent need to act, it may immediately adopt provisional measures on its territory.', 'Cooperation', 'Compliance', 2, false, 66),
  ('Art. 67', 'Exchange of Information', 'The Commission may adopt implementing acts of general scope in order to specify the arrangements for the exchange of information by electronic means between supervisory authorities.', 'Cooperation', 'Compliance', 1, false, 67),
  
  -- Chapter VIII - Remedies, Liability and Penalties
  ('Art. 68', 'European Data Protection Board', 'The European Data Protection Board is hereby established as a body of the Union with legal personality.', 'Remedies', 'Compliance', 1, false, 68),
  ('Art. 69', 'Independence', 'The Board shall act independently when performing its tasks or exercising its powers.', 'Remedies', 'Compliance', 1, false, 69),
  ('Art. 70', 'Tasks of the Board', 'The Board shall ensure the consistent application of this Regulation by: monitoring and ensuring application, advising the Commission, issuing guidelines and recommendations, reviewing legislation, establishing standard contractual clauses, maintaining public register of decisions, and promoting cooperation.', 'Remedies', 'Compliance', 2, true, 70),
  ('Art. 71', 'Reports', 'The Board shall draw up an annual report regarding the protection of natural persons with regard to processing in the Union and transmit it to the European Parliament, the Council and the Commission.', 'Remedies', 'Compliance', 1, false, 71),
  ('Art. 72', 'Procedure', 'The Board shall take decisions by a simple majority of its members, unless otherwise provided for in this Regulation.', 'Remedies', 'Compliance', 1, false, 72),
  ('Art. 73', 'Chair', 'The Board shall elect a chair and two deputy chairs from amongst its members by simple majority.', 'Remedies', 'Compliance', 1, false, 73),
  ('Art. 74', 'Tasks of the Chair', 'The Chair shall have the following tasks: convening meetings, preparing the agenda, notifying decisions to the data subjects.', 'Remedies', 'Compliance', 1, false, 74),
  ('Art. 75', 'Secretariat', 'The Board shall have a secretariat, which shall be provided by the European Data Protection Supervisor.', 'Remedies', 'Compliance', 1, false, 75),
  ('Art. 76', 'Confidentiality', 'The discussions of the Board shall be confidential where the Board deems it necessary.', 'Remedies', 'Compliance', 1, false, 76),
  ('Art. 77', 'Right to Lodge Complaint', 'Without prejudice to any other administrative or judicial remedy, every data subject shall have the right to lodge a complaint with a supervisory authority if the data subject considers that the processing infringes this Regulation.', 'Remedies', 'Legal', 3, true, 77),
  ('Art. 78', 'Right to Judicial Remedy Against Authority', 'Without prejudice to any other administrative or non-judicial remedy, each natural or legal person shall have the right to an effective judicial remedy against a legally binding decision of a supervisory authority.', 'Remedies', 'Legal', 3, true, 78),
  ('Art. 79', 'Right to Judicial Remedy Against Controller', 'Without prejudice to any available administrative or non-judicial remedy, each data subject shall have the right to an effective judicial remedy where he or she considers that his or her rights have been infringed as a result of the processing.', 'Remedies', 'Legal', 3, true, 79),
  ('Art. 80', 'Representation of Data Subjects', 'The data subject shall have the right to mandate a not-for-profit body, organisation or association to lodge the complaint on his or her behalf and to exercise rights on his or her behalf.', 'Remedies', 'Legal', 2, true, 80),
  ('Art. 81', 'Suspension of Proceedings', 'Where a competent court of a Member State has information on proceedings concerning the same subject matter as regards processing by the same controller or processor that are pending in a court in another Member State, it shall contact that court.', 'Remedies', 'Legal', 1, false, 81),
  ('Art. 82', 'Right to Compensation and Liability', 'Any person who has suffered material or non-material damage as a result of an infringement of this Regulation shall have the right to receive compensation from the controller or processor for the damage suffered.', 'Remedies', 'Legal', 3, true, 82),
  ('Art. 83', 'General Conditions for Imposing Fines', 'Infringements shall be subject to administrative fines up to 10,000,000 EUR or up to 2% of total worldwide annual turnover (whichever is higher) for some violations, and up to 20,000,000 EUR or up to 4% (whichever is higher) for more serious violations.', 'Remedies', 'Compliance', 3, true, 83),
  ('Art. 84', 'Penalties', 'Member States shall lay down the rules on other penalties applicable to infringements of this Regulation and shall take all measures necessary to ensure that they are implemented.', 'Remedies', 'Legal', 2, true, 84),
  
  -- Chapter IX - Provisions Relating to Specific Processing Situations
  ('Art. 85', 'Processing and Freedom of Expression', 'Member States shall by law reconcile the right to the protection of personal data with the right to freedom of expression and information.', 'Specific Situations', 'Legal', 2, true, 85),
  ('Art. 86', 'Processing and Public Access', 'Personal data in official documents held by a public authority may be disclosed by the authority in accordance with Union or Member State law to which the public authority is subject.', 'Specific Situations', 'Legal', 2, true, 86),
  ('Art. 87', 'Processing of National ID Number', 'Member States may further determine the specific conditions for the processing of a national identification number or any other identifier of general application.', 'Specific Situations', 'Legal', 2, false, 87),
  ('Art. 88', 'Processing in Employment Context', 'Member States may provide for more specific rules to ensure the protection of the rights and freedoms in respect of the processing of employees personal data in the employment context.', 'Specific Situations', 'Legal', 2, false, 88),
  ('Art. 89', 'Safeguards for Processing for Archiving', 'Processing for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes shall be subject to appropriate safeguards.', 'Specific Situations', 'Legal', 2, false, 89),
  ('Art. 90', 'Obligations of Secrecy', 'Member States may adopt specific rules to set out the powers of the supervisory authorities in relation to controllers or processors that are subject to an obligation of professional secrecy.', 'Specific Situations', 'Legal', 1, false, 90),
  ('Art. 91', 'Existing Data Protection Rules', 'Where in a Member State, churches and religious associations apply comprehensive rules relating to the protection of natural persons with regard to processing, such rules may continue to apply.', 'Specific Situations', 'Legal', 1, false, 91),
  
  -- Chapter X - Delegated Acts and Implementing Acts
  ('Art. 92', 'Exercise of Delegation', 'The power to adopt delegated acts is conferred on the Commission subject to the conditions laid down in this Article.', 'Delegated Acts', 'Legal', 1, false, 92),
  ('Art. 93', 'Committee Procedure', 'The Commission shall be assisted by a committee (Committee). That committee shall be a committee within the meaning of Regulation (EU) No 182/2011.', 'Delegated Acts', 'Legal', 1, false, 93),
  
  -- Chapter XI - Final Provisions
  ('Art. 94', 'Repeal of Directive 95/46/EC', 'Directive 95/46/EC is repealed with effect from 25 May 2018.', 'Final Provisions', 'Legal', 1, false, 94),
  ('Art. 95', 'Relationship with Directive 2002/58/EC', 'This Regulation shall not impose additional obligations on natural or legal persons in relation to processing in connection with the provision of publicly available electronic communications services.', 'Final Provisions', 'Legal', 1, false, 95),
  ('Art. 96', 'Relationship with Previously Concluded Agreements', 'International agreements involving the transfer of personal data to third countries concluded by Member States prior to 24 May 2016 shall remain in force until amended, replaced or revoked.', 'Final Provisions', 'Legal', 1, false, 96),
  ('Art. 97', 'Commission Reports', 'By 25 May 2020 and every four years thereafter, the Commission shall submit a report on the evaluation and review of this Regulation to the European Parliament and to the Council.', 'Final Provisions', 'Legal', 1, false, 97),
  ('Art. 98', 'Review of Other Union Legal Acts', 'The Commission shall, if appropriate, submit legislative proposals with a view to amending other Union legal acts on the protection of personal data.', 'Final Provisions', 'Legal', 1, false, 98),
  ('Art. 99', 'Entry Into Force and Application', 'This Regulation shall enter into force on the twentieth day following that of its publication in the Official Journal of the European Union. It shall apply from 25 May 2018.', 'Final Provisions', 'Legal', 1, false, 99)
) AS req(codigo, titulo, descricao, categoria, area_responsavel, peso, obrigatorio, ordem)
WHERE f.nome = 'GDPR' AND f.versao = '2018';