-- 9. ISO 9001:2015 (50 requisitos de sistema de gestão da qualidade)
INSERT INTO gap_analysis_requirements (framework_id, codigo, titulo, descricao, categoria, area_responsavel, peso, obrigatorio, ordem, created_at, updated_at)
SELECT 
  (SELECT id FROM gap_analysis_frameworks WHERE nome = 'ISO 9001' AND empresa_id IS NULL),
  codigo, titulo, descricao, categoria, 'Qualidade', peso, obrigatorio, ordem, now(), now()
FROM (VALUES
  ('4.1', 'Contexto Organização', 'Compreender contexto organizacional', 'Contexto', 3, true, 1),
  ('4.2', 'Necessidades Partes Interessadas', 'Compreender necessidades stakeholders', 'Contexto', 3, true, 2),
  ('4.3', 'Escopo SGQ', 'Determinar escopo sistema qualidade', 'Contexto', 3, true, 3),
  ('4.4', 'Sistema Gestão Qualidade', 'Estabelecer e manter SGQ', 'Contexto', 3, true, 4),
  ('5.1', 'Liderança Compromisso', 'Alta direção demonstra liderança', 'Liderança', 3, true, 5),
  ('5.2', 'Foco Cliente', 'Focar em satisfação cliente', 'Liderança', 3, true, 6),
  ('5.3', 'Política Qualidade', 'Estabelecer política da qualidade', 'Liderança', 3, true, 7),
  ('5.4', 'Papéis Responsabilidades', 'Atribuir responsabilidades', 'Liderança', 3, true, 8),
  ('6.1', 'Ações Riscos Oportunidades', 'Planejar ações para riscos', 'Planejamento', 3, true, 9),
  ('6.2', 'Objetivos Qualidade', 'Estabelecer objetivos qualidade', 'Planejamento', 3, true, 10),
  ('6.3', 'Planejamento Mudanças', 'Planejar mudanças no SGQ', 'Planejamento', 2, true, 11),
  ('7.1.1', 'Recursos Gerais', 'Determinar e prover recursos', 'Apoio', 2, true, 12),
  ('7.1.2', 'Pessoas', 'Assegurar pessoas competentes', 'Apoio', 3, true, 13),
  ('7.1.3', 'Infraestrutura', 'Manter infraestrutura adequada', 'Apoio', 2, true, 14),
  ('7.1.4', 'Ambiente Processos', 'Manter ambiente adequado', 'Apoio', 2, true, 15),
  ('7.1.5', 'Recursos Monitoramento', 'Prover recursos monitoramento', 'Apoio', 2, true, 16),
  ('7.1.6', 'Conhecimento Organizacional', 'Gerenciar conhecimento', 'Apoio', 2, true, 17),
  ('7.2', 'Competência', 'Assegurar competência', 'Apoio', 3, true, 18),
  ('7.3', 'Conscientização', 'Assegurar conscientização', 'Apoio', 2, true, 19),
  ('7.4', 'Comunicação', 'Determinar comunicações', 'Apoio', 2, true, 20),
  ('7.5', 'Informação Documentada', 'Controlar documentos', 'Apoio', 2, true, 21),
  ('8.1', 'Planejamento Controle Operacional', 'Planejar e controlar operações', 'Operação', 3, true, 22),
  ('8.2', 'Requisitos Produtos Serviços', 'Determinar requisitos', 'Operação', 3, true, 23),
  ('8.3', 'Projeto Desenvolvimento', 'Projetar e desenvolver', 'Operação', 2, true, 24),
  ('8.4', 'Controle Provedores Externos', 'Controlar fornecedores', 'Operação', 3, true, 25),
  ('8.5', 'Produção Provisão Serviços', 'Controlar produção serviços', 'Operação', 3, true, 26),
  ('8.6', 'Liberação Produtos Serviços', 'Liberar produtos e serviços', 'Operação', 3, true, 27),
  ('8.7', 'Controle Saídas Não Conformes', 'Controlar não conformidades', 'Operação', 3, true, 28),
  ('9.1', 'Monitoramento Medição', 'Monitorar e medir SGQ', 'Avaliação', 3, true, 29),
  ('9.2', 'Auditoria Interna', 'Conduzir auditorias internas', 'Avaliação', 3, true, 30),
  ('9.3', 'Análise Crítica Direção', 'Alta direção analisa criticamente', 'Avaliação', 3, true, 31),
  ('10.1', 'Não Conformidade Ação Corretiva', 'Tratar não conformidades', 'Melhoria', 3, true, 32),
  ('10.2', 'Melhoria Contínua', 'Melhorar continuamente', 'Melhoria', 2, true, 33),
  ('10.3', 'Inovação', 'Promover inovação', 'Melhoria', 2, true, 34),
  ('8.2.1', 'Comunicação Cliente', 'Comunicar com clientes', 'Operação', 2, true, 35),
  ('8.2.2', 'Determinação Requisitos', 'Determinar requisitos', 'Operação', 3, true, 36),
  ('8.2.3', 'Análise Crítica Requisitos', 'Revisar requisitos', 'Operação', 3, true, 37),
  ('8.2.4', 'Mudanças Requisitos', 'Gerenciar mudanças requisitos', 'Operação', 2, true, 38),
  ('8.3.1', 'Planejamento Projeto', 'Planejar projeto e desenvolvimento', 'Operação', 2, true, 39),
  ('8.3.2', 'Entradas Projeto', 'Determinar entradas projeto', 'Operação', 2, true, 40),
  ('8.3.3', 'Controles Projeto', 'Controlar projeto', 'Operação', 2, true, 41),
  ('8.3.4', 'Saídas Projeto', 'Determinar saídas projeto', 'Operação', 2, true, 42),
  ('8.3.5', 'Mudanças Projeto', 'Controlar mudanças projeto', 'Operação', 2, true, 43),
  ('8.5.1', 'Controle Produção', 'Controlar produção', 'Operação', 3, true, 44),
  ('8.5.2', 'Identificação Rastreabilidade', 'Identificar e rastrear', 'Operação', 2, true, 45),
  ('8.5.3', 'Propriedade Cliente', 'Proteger propriedade cliente', 'Operação', 2, true, 46),
  ('8.5.4', 'Preservação', 'Preservar saídas processo', 'Operação', 2, true, 47),
  ('8.5.5', 'Atividades Pós-Entrega', 'Gerenciar atividades pós-entrega', 'Operação', 2, true, 48),
  ('8.5.6', 'Controle Mudanças', 'Controlar mudanças', 'Operação', 3, true, 49),
  ('9.1.1', 'Satisfação Cliente', 'Monitorar satisfação cliente', 'Avaliação', 3, true, 50)
) AS t(codigo, titulo, descricao, categoria, peso, obrigatorio, ordem)
ON CONFLICT DO NOTHING;